import { widgetById, widgets, type Widget } from "./statusLineWidgets";

export type StatusLineConfig = {
  widgets: string[];
  separator: string;
  refreshInterval?: number;
  padding?: number;
};

export const DEFAULT_CONFIG: StatusLineConfig = {
  widgets: ["model", "context-percent", "session-cost"],
  separator: " · ",
  refreshInterval: undefined,
  padding: 0,
};

const CONFIG_MARKER = "# CCM-CONFIG:";

/**
 * Generate the full ~/.claude/statusline.sh script from a config.
 * Embeds the config as a comment so we can round-trip it from disk.
 */
export function generateScript(cfg: StatusLineConfig): string {
  const selected: Widget[] = cfg.widgets
    .map((id) => widgetById[id])
    .filter((w): w is Widget => Boolean(w));

  const cfgJson = JSON.stringify({
    widgets: cfg.widgets,
    separator: cfg.separator,
    refreshInterval: cfg.refreshInterval,
    padding: cfg.padding,
  });

  // Escape the separator for embedding in a bash double-quoted string.
  // The simplest path: write it as a raw bash literal by escaping " and \.
  const sepLiteral = cfg.separator
    .replace(/\\/g, "\\\\")
    .replace(/"/g, '\\"');

  const partBlocks = selected
    .map(
      (w, i) => `
# ── ${w.label} (${w.id}) ──────────────────────────────
PART_${i}=$( {
${indent(w.shell, "  ")}
} 2>/dev/null )
[ -n "\${PART_${i}}" ] && parts+=("\${PART_${i}}")`,
    )
    .join("\n");

  return `#!/usr/bin/env bash
${CONFIG_MARKER} ${cfgJson}
# Generated by claude-config-ui (https://github.com/HarshitSingh-PM/claude-config-manager).
# Edit via the Status Line tab in the UI to regenerate. Manual edits below the
# marker are safe; the next regeneration will preserve nothing — back up if you
# customize.

set +e
INPUT=$(cat)
SEP="${sepLiteral}"

parts=()
${partBlocks}

# Join parts with the configured separator
out=""
for p in "\${parts[@]}"; do
  if [ -n "$out" ]; then
    out="\${out}\${SEP}\${p}"
  else
    out="$p"
  fi
done

# Status line goes to stdout; stderr is discarded by Claude Code anyway.
printf '%s\\n' "$out"
`;
}

function indent(s: string, prefix: string): string {
  return s
    .split("\n")
    .map((l) => (l.length ? prefix + l : l))
    .join("\n");
}

/**
 * Try to parse a previously-generated script back into a config. Returns null
 * if the marker isn't found (the user wrote their own script, we shouldn't
 * trample it).
 */
export function parseScript(content: string): StatusLineConfig | null {
  if (!content) return null;
  for (const line of content.split("\n").slice(0, 20)) {
    if (line.startsWith(CONFIG_MARKER)) {
      try {
        const json = line.slice(CONFIG_MARKER.length).trim();
        const cfg = JSON.parse(json) as Partial<StatusLineConfig>;
        if (Array.isArray(cfg.widgets) && typeof cfg.separator === "string") {
          return {
            widgets: cfg.widgets.filter((id): id is string => typeof id === "string"),
            separator: cfg.separator,
            refreshInterval: cfg.refreshInterval,
            padding: cfg.padding ?? 0,
          };
        }
      } catch {
        /* fall through */
      }
    }
  }
  return null;
}

/**
 * What the rendered status line would look like with example data. Used for
 * the realtime preview pane in the UI.
 */
export function renderPreview(cfg: StatusLineConfig): string {
  const parts = cfg.widgets
    .map((id) => widgetById[id]?.preview)
    .filter((p): p is string => Boolean(p));
  return parts.join(cfg.separator);
}

/** Aggregate the external dependencies of a config (jq / ccusage / git / …). */
export function configDeps(cfg: StatusLineConfig): string[] {
  const set = new Set<string>();
  for (const id of cfg.widgets) {
    for (const d of widgetById[id]?.deps ?? []) set.add(d);
  }
  return Array.from(set);
}

/** True if any selected widget needs settings.json refreshInterval to feel live. */
export function configNeedsRefresh(cfg: StatusLineConfig): boolean {
  return cfg.widgets.some((id) => widgetById[id]?.needsRefresh);
}

// Re-export so the form can iterate.
export { widgets };
