"use client";
import { useEffect, useMemo, useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Plus,
  Trash2,
  ArrowUp,
  ArrowDown,
  Sparkles,
  Eye,
  AlertTriangle,
  RefreshCw,
  Terminal,
  Save,
  RotateCcw,
  Code2,
} from "lucide-react";
import { Card, IconButton, TextInput } from "../primitives";
import { InfoIcon, Tooltip } from "../Tooltip";
import {
  widgets,
  widgetById,
  categoryLabels,
  type WidgetCategory,
} from "@/lib/statusLineWidgets";
import {
  DEFAULT_CONFIG,
  generateScript,
  parseScript,
  renderPreview,
  configDeps,
  configNeedsRefresh,
  type StatusLineConfig,
} from "@/lib/statusLineGenerator";
import { statusLineTemplates } from "@/lib/presets/statusLineTemplates";
import { stringifyConfig, safeParseJson } from "@/lib/utils";

type Props = {
  scriptPath: string;        // ~/.claude/statusline.sh
  settingsPath: string;      // ~/.claude/settings.json
  onSaved: (msg: string) => void;
  onError: (msg: string) => void;
};

export function StatusLineForm({ scriptPath, settingsPath, onSaved, onError }: Props) {
  const [config, setConfig] = useState<StatusLineConfig>(DEFAULT_CONFIG);
  const [loadedConfig, setLoadedConfig] = useState<StatusLineConfig | null>(null);
  const [exists, setExists] = useState(false);
  const [loading, setLoading] = useState(true);
  const [saving, setSaving] = useState(false);
  const [showScript, setShowScript] = useState(false);
  const [unrecognized, setUnrecognized] = useState<string | null>(null);
  // The status line in settings.json may not currently point at our script —
  // surface that so we can offer to fix it.
  const [currentStatusLine, setCurrentStatusLine] = useState<{
    type?: string;
    command?: string;
  } | null>(null);

  // ── Load: fetch script (if any) + settings.json statusLine ─────────
  useEffect(() => {
    let cancelled = false;
    async function go() {
      setLoading(true);
      const [scriptRes, settingsRes] = await Promise.all([
        fetch(`/api/file?path=${encodeURIComponent(scriptPath)}`).then((r) => r.json()),
        fetch(`/api/file?path=${encodeURIComponent(settingsPath)}`).then((r) => r.json()),
      ]);
      if (cancelled) return;
      const scriptContent = (scriptRes.content as string | undefined) ?? "";
      const parsed = parseScript(scriptContent);
      if (parsed) {
        setConfig(parsed);
        setLoadedConfig(parsed);
        setUnrecognized(null);
      } else if (scriptContent.trim()) {
        // A statusline.sh exists but wasn't generated by this tool.
        setUnrecognized(scriptContent);
        setLoadedConfig(null);
      } else {
        setLoadedConfig(null);
      }
      setExists(Boolean(scriptRes.exists));

      const settings = safeParseJson((settingsRes.content as string | undefined) ?? "");
      const sl = settings.statusLine as { type?: string; command?: string } | undefined;
      setCurrentStatusLine(sl ?? null);

      setLoading(false);
    }
    go();
    return () => {
      cancelled = true;
    };
  }, [scriptPath, settingsPath]);

  const dirty = useMemo(() => {
    if (!loadedConfig) return config.widgets.length > 0;
    return (
      JSON.stringify(loadedConfig) !== JSON.stringify(config) ||
      !pointsAtScript(currentStatusLine, scriptPath, config.refreshInterval, config.padding)
    );
  }, [loadedConfig, config, currentStatusLine, scriptPath]);

  const preview = renderPreview(config);
  const deps = configDeps(config);
  const needsRefresh = configNeedsRefresh(config);

  const addWidget = (id: string) => {
    if (config.widgets.includes(id)) return;
    setConfig({ ...config, widgets: [...config.widgets, id] });
  };
  const removeWidget = (id: string) => {
    setConfig({ ...config, widgets: config.widgets.filter((x) => x !== id) });
  };
  const moveWidget = (id: string, dir: -1 | 1) => {
    const idx = config.widgets.indexOf(id);
    if (idx < 0) return;
    const next = [...config.widgets];
    const swap = idx + dir;
    if (swap < 0 || swap >= next.length) return;
    [next[idx], next[swap]] = [next[swap], next[idx]];
    setConfig({ ...config, widgets: next });
  };
  const applyTemplate = (tplId: string) => {
    const t = statusLineTemplates.find((x) => x.id === tplId);
    if (!t) return;
    if (
      config.widgets.length > 0 &&
      !confirm(`Replace the current selection with the "${t.title}" template?`)
    ) {
      return;
    }
    setConfig({
      widgets: [...t.widgets],
      separator: t.separator,
      refreshInterval: t.refreshInterval,
      padding: 0,
    });
  };

  const save = async () => {
    if (config.widgets.length === 0) {
      onError("Add at least one widget before saving.");
      return;
    }
    setSaving(true);
    try {
      // 1. Write the script
      const script = generateScript(config);
      const scriptRes = await fetch("/api/file", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ path: scriptPath, content: script, backup: true }),
      });
      const scriptData = await scriptRes.json();
      if (!scriptRes.ok) {
        onError(`Failed to write script: ${scriptData.error ?? "unknown"}`);
        return;
      }

      // 2. Update settings.json statusLine. We invoke via `bash <path>` so the
      // script doesn't need a +x bit (the file API can't chmod), and so that
      // Claude Code's command parsing is unambiguous across versions.
      const settingsRes = await fetch(
        `/api/file?path=${encodeURIComponent(settingsPath)}`,
      ).then((r) => r.json());
      const settings = safeParseJson(
        (settingsRes.content as string | undefined) ?? "",
      );
      const newStatusLine: Record<string, unknown> = {
        type: "command",
        command: `bash ${scriptPath}`,
      };
      if (config.refreshInterval) newStatusLine.refreshInterval = config.refreshInterval;
      if (config.padding) newStatusLine.padding = config.padding;
      settings.statusLine = newStatusLine;
      const writeRes = await fetch("/api/file", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          path: settingsPath,
          content: stringifyConfig(settings),
          backup: true,
        }),
      });
      const writeData = await writeRes.json();
      if (!writeRes.ok) {
        onError(`Wrote script, but failed to update settings.json: ${writeData.error ?? "unknown"}`);
        return;
      }

      onSaved(
        `Saved. Restart Claude Code (or start a fresh session) to see the new status line.`,
      );
      setLoadedConfig(config);
      setExists(true);
      setCurrentStatusLine(newStatusLine);
    } catch (err) {
      onError(String(err));
    } finally {
      setSaving(false);
    }
  };

  const discard = () => {
    if (loadedConfig) setConfig(loadedConfig);
    else setConfig(DEFAULT_CONFIG);
  };

  if (loading) {
    return (
      <Card className="p-10 text-center text-xs text-[color:var(--fg-muted)]">
        Loading status line config…
      </Card>
    );
  }

  return (
    <div className="space-y-5">
      {/* ─── Live preview pane ──────────────────────────────── */}
      <Card className="p-0 overflow-hidden">
        <div className="flex items-center justify-between px-4 py-2 border-b border-[color:var(--border)] bg-[color:var(--bg-elev-2)]/40">
          <div className="flex items-center gap-1.5">
            <Eye size={13} className="text-[color:var(--accent)]" />
            <h3 className="text-xs font-medium">Live preview</h3>
            <InfoIcon
              content="Mock render with realistic values. The actual values come from the JSON Claude Code pipes to your script on every prompt."
              significance="If a widget has dependencies you don't have installed (jq / ccusage / git), it'll just be skipped at runtime — no error."
            />
          </div>
          <div className="flex items-center gap-2 text-[10px] text-[color:var(--fg-faint)]">
            <Terminal size={11} />
            <span className="font-mono">~/.claude/statusline.sh</span>
          </div>
        </div>
        <div className="px-4 py-5 bg-[#0d0d10] font-mono text-sm">
          <div className="text-[color:var(--fg-faint)] text-[11px] mb-1.5">
            $ claude
          </div>
          <div className="text-[color:var(--fg)] whitespace-pre-wrap break-all">
            {preview || (
              <span className="text-[color:var(--fg-faint)] italic">
                (empty — pick a widget below)
              </span>
            )}
          </div>
          <div className="text-[color:var(--fg-faint)] text-[11px] mt-2">
            <span className="text-[color:var(--accent)]">›</span> Hello Claude
          </div>
        </div>
        {(deps.length > 0 || needsRefresh || unrecognized) && (
          <div className="px-4 py-2.5 border-t border-[color:var(--border)] space-y-1 text-[11px]">
            {deps.length > 0 && (
              <div className="text-[color:var(--fg-muted)] flex items-center gap-1.5">
                <span className="text-[color:var(--fg-faint)]">Needs installed:</span>
                {deps.map((d) => (
                  <code
                    key={d}
                    className="px-1.5 py-0.5 rounded bg-[color:var(--bg-elev-2)] border border-[color:var(--border)] text-[color:var(--fg)]"
                  >
                    {d}
                  </code>
                ))}
              </div>
            )}
            {needsRefresh && (
              <div className="text-[color:var(--warning)] flex items-center gap-1.5">
                <RefreshCw size={11} />
                <span>
                  Clock/battery widgets need <code>refreshInterval</code> set —
                  add a value below to keep them live.
                </span>
              </div>
            )}
            {unrecognized && (
              <div className="text-[color:var(--warning)] flex items-start gap-1.5">
                <AlertTriangle size={11} className="mt-0.5 shrink-0" />
                <span>
                  An existing <code>statusline.sh</code> exists but wasn&apos;t generated by
                  this tool. Saving will overwrite it (with a <code>.bak</code>).
                </span>
              </div>
            )}
          </div>
        )}
      </Card>

      {/* ─── Action bar ─────────────────────────────────────── */}
      <Card className="p-4 flex items-center justify-between gap-3">
        <div className="text-[11px] text-[color:var(--fg-muted)]">
          {dirty ? (
            <span className="text-[color:var(--warning)]">Unsaved changes</span>
          ) : exists ? (
            <span className="text-[color:var(--success)]">Synced with disk</span>
          ) : (
            <span>Will create {scriptPath}</span>
          )}
        </div>
        <div className="flex items-center gap-2">
          <button
            onClick={() => setShowScript((x) => !x)}
            className="inline-flex items-center gap-1.5 text-xs px-2.5 h-7 rounded-md border border-[color:var(--border)] text-[color:var(--fg-muted)] hover:text-[color:var(--fg)] transition"
          >
            <Code2 size={11} /> {showScript ? "Hide" : "Show"} generated script
          </button>
          <button
            onClick={discard}
            disabled={!dirty}
            className="inline-flex items-center gap-1.5 text-xs px-2.5 h-7 rounded-md border border-[color:var(--border)] text-[color:var(--fg-muted)] hover:text-[color:var(--fg)] transition disabled:opacity-30 disabled:cursor-not-allowed"
          >
            <RotateCcw size={11} /> Discard
          </button>
          <button
            onClick={save}
            disabled={!dirty || saving || config.widgets.length === 0}
            className="inline-flex items-center gap-1.5 text-xs px-3 h-7 rounded-md bg-[color:var(--accent)] text-[color:var(--accent-ink)] font-medium hover:bg-[color:var(--accent-2)] transition disabled:opacity-30 disabled:cursor-not-allowed"
          >
            <Save size={11} /> {saving ? "Saving…" : "Save & install"}
          </button>
        </div>
      </Card>

      <AnimatePresence>
        {showScript && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }}
            className="overflow-hidden"
          >
            <Card className="p-0 overflow-hidden">
              <div className="px-4 py-2 text-[11px] text-[color:var(--fg-muted)] border-b border-[color:var(--border)] bg-[color:var(--bg-elev-2)]/40">
                Generated script — this is exactly what will be written to {scriptPath}
              </div>
              <pre className="px-4 py-3 text-[11.5px] font-mono leading-relaxed overflow-x-auto max-h-[400px]">
                {generateScript(config)}
              </pre>
            </Card>
          </motion.div>
        )}
      </AnimatePresence>

      {/* ─── Two-column: selected widgets + catalog ─────────── */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-5">
        <SelectedWidgetsPanel
          config={config}
          setConfig={setConfig}
          moveWidget={moveWidget}
          removeWidget={removeWidget}
        />
        <CatalogPanel selected={config.widgets} addWidget={addWidget} />
      </div>

      {/* ─── Templates ──────────────────────────────────────── */}
      <Card className="p-4">
        <div className="flex items-center gap-1.5 mb-3">
          <Sparkles size={14} className="text-[color:var(--accent)]" />
          <h3 className="text-sm font-medium">Templates</h3>
          <InfoIcon
            content="Replaces the current selection with a curated widget set."
            significance="Pick a starting point, then add/remove individual widgets to taste."
          />
        </div>
        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-2">
          {statusLineTemplates.map((t) => (
            <motion.button
              key={t.id}
              whileHover={{ y: -1 }}
              whileTap={{ scale: 0.99 }}
              onClick={() => applyTemplate(t.id)}
              className="text-left px-3 py-2.5 rounded-lg border border-[color:var(--border)] hover:border-[color:var(--accent)]/50 hover:bg-[color:var(--accent-soft)] transition"
            >
              <div className="text-xs font-medium text-[color:var(--fg)]">{t.title}</div>
              <div className="text-[11px] text-[color:var(--fg-muted)] mt-0.5 leading-relaxed">
                {t.description}
              </div>
              <div className="text-[10px] text-[color:var(--fg-faint)] mt-1 font-mono">
                {t.source}
              </div>
            </motion.button>
          ))}
        </div>
      </Card>
    </div>
  );
}

function pointsAtScript(
  current: { type?: string; command?: string } | null,
  scriptPath: string,
  refreshInterval?: number,
  padding?: number,
): boolean {
  if (!current) return false;
  if (current.type !== "command") return false;
  // Accept either form: "bash <path>" (what we write) OR bare "<path>" (legacy).
  const cmd = (current.command ?? "").trim();
  const matchesBash = cmd === `bash ${scriptPath}` || cmd === `bash "${scriptPath}"`;
  const matchesBare = cmd === scriptPath;
  if (!matchesBash && !matchesBare) return false;
  if (refreshInterval !== undefined) {
    if ((current as { refreshInterval?: number }).refreshInterval !== refreshInterval) return false;
  }
  if (padding) {
    if ((current as { padding?: number }).padding !== padding) return false;
  }
  return true;
}

function SelectedWidgetsPanel({
  config,
  setConfig,
  moveWidget,
  removeWidget,
}: {
  config: StatusLineConfig;
  setConfig: (c: StatusLineConfig) => void;
  moveWidget: (id: string, dir: -1 | 1) => void;
  removeWidget: (id: string) => void;
}) {
  return (
    <Card className="p-4">
      <div className="flex items-center justify-between mb-3">
        <h3 className="text-sm font-medium inline-flex items-center gap-1.5">
          Selected widgets
          <InfoIcon
            content="Widgets render in this order, joined by your separator."
            significance="Reorder with the arrows. Each save regenerates the script."
          />
        </h3>
        <span className="text-[11px] text-[color:var(--fg-muted)]">
          {config.widgets.length} selected
        </span>
      </div>

      <div className="space-y-1.5 mb-4 min-h-[60px]">
        <AnimatePresence initial={false}>
          {config.widgets.map((id, idx) => {
            const w = widgetById[id];
            if (!w) return null;
            return (
              <motion.div
                key={id}
                layout
                initial={{ opacity: 0, y: -4 }}
                animate={{ opacity: 1, y: 0 }}
                exit={{ opacity: 0 }}
                className="flex items-center gap-2 px-2.5 py-2 rounded-md bg-[color:var(--bg-elev-2)] border border-[color:var(--border)]"
              >
                <span className="text-[10px] font-mono text-[color:var(--fg-faint)] w-4">
                  {idx + 1}
                </span>
                <div className="flex-1 min-w-0">
                  <div className="text-xs font-medium truncate">{w.label}</div>
                  <code className="text-[10.5px] text-[color:var(--accent)] font-mono">
                    {w.preview}
                  </code>
                </div>
                <IconButton
                  label="Move up"
                  onClick={() => moveWidget(id, -1)}
                  disabled={idx === 0}
                >
                  <ArrowUp size={12} />
                </IconButton>
                <IconButton
                  label="Move down"
                  onClick={() => moveWidget(id, 1)}
                  disabled={idx === config.widgets.length - 1}
                >
                  <ArrowDown size={12} />
                </IconButton>
                <IconButton
                  label="Remove"
                  variant="danger"
                  onClick={() => removeWidget(id)}
                >
                  <Trash2 size={12} />
                </IconButton>
              </motion.div>
            );
          })}
        </AnimatePresence>
        {config.widgets.length === 0 && (
          <div className="text-center py-6 text-[11px] text-[color:var(--fg-faint)]">
            Pick widgets from the catalog →
          </div>
        )}
      </div>

      <div className="space-y-3 pt-3 border-t border-[color:var(--border)]">
        <div>
          <div className="flex items-center gap-1.5 mb-1.5">
            <label className="text-xs font-medium">Separator</label>
            <InfoIcon
              content="String inserted between widgets. Common choices: ' · ' (middot), ' │ ' (box-drawing pipe), ' | ', '  '."
            />
          </div>
          <TextInput
            value={config.separator}
            onChange={(v) => setConfig({ ...config, separator: v })}
            monospaced
            placeholder=" │ "
          />
        </div>

        <div>
          <div className="flex items-center gap-1.5 mb-1.5">
            <label className="text-xs font-medium">Refresh interval (seconds)</label>
            <InfoIcon
              content="If set, settings.json gets `statusLine.refreshInterval`. Keeps clock/battery widgets ticking while you're idle."
              significance="Min 1. Leave empty if you don't need a clock — saves CPU on every refresh."
            />
          </div>
          <input
            type="number"
            min={1}
            value={config.refreshInterval ?? ""}
            placeholder="(unset)"
            onChange={(e) => {
              const n = e.target.value === "" ? undefined : Number(e.target.value);
              setConfig({ ...config, refreshInterval: n });
            }}
            className="w-32 bg-[color:var(--bg-elev-2)] border border-[color:var(--border)] rounded-md px-3 py-1.5 text-sm focus:border-[color:var(--accent)] transition"
          />
        </div>

        <div>
          <div className="flex items-center gap-1.5 mb-1.5">
            <label className="text-xs font-medium">Padding</label>
            <InfoIcon content="Horizontal padding in characters before/after the line." />
          </div>
          <input
            type="number"
            min={0}
            value={config.padding ?? 0}
            onChange={(e) =>
              setConfig({ ...config, padding: Number(e.target.value) || 0 })
            }
            className="w-32 bg-[color:var(--bg-elev-2)] border border-[color:var(--border)] rounded-md px-3 py-1.5 text-sm focus:border-[color:var(--accent)] transition"
          />
        </div>
      </div>
    </Card>
  );
}

function CatalogPanel({
  selected,
  addWidget,
}: {
  selected: string[];
  addWidget: (id: string) => void;
}) {
  const byCategory: Record<WidgetCategory, typeof widgets> = {
    session: [],
    context: [],
    cost: [],
    quota: [],
    project: [],
    git: [],
    system: [],
  };
  for (const w of widgets) byCategory[w.category].push(w);

  return (
    <Card className="p-4">
      <div className="flex items-center justify-between mb-3">
        <h3 className="text-sm font-medium inline-flex items-center gap-1.5">
          Widget catalog
          <InfoIcon
            content="Click a widget to add it to your status line."
            significance="Categories match Claude Code's stdin contract — session info, context window, cost, rate limits, etc."
          />
        </h3>
        <span className="text-[11px] text-[color:var(--fg-muted)]">
          {widgets.length} widgets
        </span>
      </div>
      <div className="space-y-3.5 max-h-[640px] overflow-y-auto pr-1">
        {(Object.keys(byCategory) as WidgetCategory[]).map((cat) => (
          <div key={cat}>
            <div className="text-[10px] uppercase tracking-wide text-[color:var(--fg-faint)] mb-1.5 flex items-center gap-1.5">
              <span>{categoryLabels[cat].emoji}</span>
              <span>{categoryLabels[cat].label}</span>
            </div>
            <div className="space-y-1">
              {byCategory[cat].map((w) => {
                const inUse = selected.includes(w.id);
                return (
                  <Tooltip
                    key={w.id}
                    content={w.description}
                    significance={
                      w.deps?.length
                        ? `Requires: ${w.deps.join(", ")}`
                        : undefined
                    }
                  >
                    <motion.button
                      whileHover={{ x: 2 }}
                      whileTap={{ scale: 0.98 }}
                      onClick={() => addWidget(w.id)}
                      disabled={inUse}
                      className={`w-full text-left px-2.5 py-1.5 rounded-md border transition flex items-center gap-2 ${
                        inUse
                          ? "border-[color:var(--accent)]/30 bg-[color:var(--accent-soft)]/30 opacity-60"
                          : "border-transparent hover:border-[color:var(--accent)]/40 hover:bg-[color:var(--accent-soft)]"
                      }`}
                    >
                      <div className="flex-1 min-w-0">
                        <div className="text-xs text-[color:var(--fg)] flex items-center gap-1.5">
                          {w.label}
                          {w.deps?.includes("ccusage") && (
                            <span className="text-[9px] uppercase text-[color:var(--warning)] border border-[color:var(--warning)]/40 px-1 py-px rounded">
                              ccusage
                            </span>
                          )}
                          {w.needsRefresh && (
                            <span className="text-[9px] uppercase text-[color:var(--accent)] border border-[color:var(--accent)]/40 px-1 py-px rounded">
                              live
                            </span>
                          )}
                        </div>
                        <code className="text-[10.5px] text-[color:var(--fg-muted)] font-mono">
                          {w.preview}
                        </code>
                      </div>
                      {inUse ? (
                        <span className="text-[10px] text-[color:var(--accent)]">
                          added
                        </span>
                      ) : (
                        <Plus size={11} className="text-[color:var(--fg-faint)]" />
                      )}
                    </motion.button>
                  </Tooltip>
                );
              })}
            </div>
          </div>
        ))}
      </div>
    </Card>
  );
}
